USE [master]
GO

/****** Object:  Database [metronic]    Script Date: 7/6/2022 01:39:34 ******/
CREATE DATABASE [metronic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'metronic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\metronic.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'metronic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\metronic_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [metronic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [metronic] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [metronic] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [metronic] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [metronic] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [metronic] SET ARITHABORT OFF 
GO

ALTER DATABASE [metronic] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [metronic] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [metronic] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [metronic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [metronic] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [metronic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [metronic] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [metronic] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [metronic] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [metronic] SET  DISABLE_BROKER 
GO

ALTER DATABASE [metronic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [metronic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [metronic] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [metronic] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [metronic] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [metronic] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [metronic] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [metronic] SET RECOVERY FULL 
GO

ALTER DATABASE [metronic] SET  MULTI_USER 
GO

ALTER DATABASE [metronic] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [metronic] SET DB_CHAINING OFF 
GO

ALTER DATABASE [metronic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [metronic] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [metronic] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [metronic] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [metronic] SET QUERY_STORE = OFF
GO

ALTER DATABASE [metronic] SET  READ_WRITE 
GO


